name: 构建APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: 构建APK
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: 设置Android SDK
        uses: android-actions/setup-android@v3
          
      - name: 设置Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: 授予Gradle执行权限
        run: chmod +x gradlew
        
      - name: 构建APK
        run: ./gradlew assembleRelease
        
      - name: 签名APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: MuXuanZhuangQi
          path: app/build/outputs/apk/release/app-release-signed.apk
          if-no-files-found: error
          retention-days: 90
          
      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          name: MuXuanZhuangQi
          path: download
          
      - name: 创建Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
