name: 构建APK

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: 构建APK
    runs-on: windows-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: 设置Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: 授予Gradle执行权限
        run: chmod +x gradlew
        
      - name: 构建APK
        run: ./gradlew assembleRelease
        
      - name: 签名APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: 重命名APK
        run: |
          $VERSION=$(./gradlew -q printVersionName)
          mv app/build/outputs/apk/release/app-release-signed.apk app/build/outputs/apk/release/MuXuanZhuangQi-$VERSION.apk
          
      - name: 上传APK
        uses: actions/upload-artifact@v4
        with:
          name: MuXuanZhuangQi
          path: app/build/outputs/apk/release/MuXuanZhuangQi-*.apk
          
      - name: 创建Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/MuXuanZhuangQi-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
