name: 构建APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: 构建APK
    runs-on: ubuntu-latest

    steps:
      # 新增：取消正在进行中的相同工作流
      - name: 取消先前的工作流运行
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: 检出代码
        uses: actions/checkout@v4
      # ... a lot of existing steps ...

      - name: 创建Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/app-release*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
